### ISSUE TITLE
uncaughtException AssertionError [ERR_ASSERTION]: 2498 == 0

### ISSUE THREAD

**Issue by ccppvv** [apptools-lab/AppToolkit#81]
[2021-11-19 16:48:22.287] [error] uncaughtException AssertionError [ERR_ASSERTION]: 2498 == 0
    at ClientRequest.onConnect (/Applications/AppToolkit.app/Contents/Resources/app.asar/node_modules/tunnel-agent/index.js:160:14)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at Socket.socketOnData (_http_client.js:547:11)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
![image](https://user-images.githubusercontent.com/40158287/142595177-96aa4129-2f64-4187-8620-5ae057304593.png)

**Comment by luhc228** [comment]
如何复现的？

**Comment by ccppvv** [comment]
> 感谢反馈，这个怎么能复现，我本地看下问题

我在鹅厂，内网所有请求都被代理走某个特定端口。怀疑和这个有关。
