### ISSUE TITLE
yarn start报错 HookWebpackError: __dirname is not defined

### ISSUE THREAD

**Issue by careteenL** [apptools-lab/AppToolkit#84]
```shell
yarn setup
yarn start
```

报错信息如下：

Uncaught Error: Module build failed (from ./node_modules/@builder/pack/deps/mini-css-extract-plugin/loader.js):
HookWebpackError: __dirname is not defined
    at tryRunOrWebpackError (/Users/careteen/Desktop/careteen/AppToolkit/renderer/node_modules/@builder/pack/deps/webpack/bundle5.js:67336:9)
    at __webpack_require_module__ (/Users/careteen/Desktop/careteen/AppToolkit/renderer/node_modules/@builder/pack/deps/webpack/bundle5.js:53140:12)
    at __nested_webpack_require_150834__ (/Users/careteen/Desktop/careteen/AppToolkit/renderer/node_modules/@builder/pack/deps/webpack/bundle5.js:53097:18)
    at Module.<anonymous> (/Users/careteen/Desktop/careteen/AppToolkit/renderer/node_modules/@builder/pack/deps/css-loader/cjs.js??ruleSet[1].rules[2].use[1]!/Users/careteen/Desktop/careteen/AppToolkit/renderer/node_modules/@builder/pack/deps/postcss-loader/cjs.js??ruleSet[1].rules[2].use[2]!/Users/careteen/Desktop/careteen/AppToolkit/renderer/node_modules/build-plugin-fusion/lib/webpackLoaders/unicodeLoader.js!/Users/careteen/Desktop/careteen/AppToolkit/renderer/node_modules/@builder/pack/deps/sass-loader/cjs.js??ruleSet[1].rules[2].use[4]!/Users/careteen/Desktop/careteen/AppToolkit/renderer/node_modules/ice-skin-loader/lib/index.js??ruleSet[1].rules[2].use[5]!/Users/careteen/Desktop/careteen/AppToolkit/renderer/src/global.scss:5:126)
    
   
![screenshot-20211202-142240](https://user-images.githubusercontent.com/23131426/144369071-db410c81-7d21-40ab-a7dc-6621a262ea3c.png)

**Comment by careteenL** [comment]
### 如果将`ice.js`版本锁定在`2.0.0`则可以正常启动，但是当`yarn build`时又会报错


info 使用 Fusion 组件主题包： @alifd/theme-design-pro
info 离线化构建项目，自动下载网络资源，请耐心等待 
info esbuild is specified as default minification 
ERR! CONFIG Failed to get config.
ERR! Cannot read property 'ProgressPlugin' of undefined 
TypeError: Cannot read property 'ProgressPlugin' of undefined
    at new SimpleProgressPlugin (/Users/careteen/Desktop/sohu/fe-base/FocusAppToolkit/renderer/node_modules/@builder/pack/deps/webpack-simple-progress-plugin/index.js:1:3316)
    at /Users/careteen/Desktop/sohu/fe-base/FocusAppToolkit/renderer/node_modules/@builder/pack/deps/webpack-chain/Config.js:1:20276
    at Object.toConfig (/Users/careteen/Desktop/sohu/fe-base/FocusAppToolkit/renderer/node_modules/@builder/pack/deps/webpack-chain/Config.js:1:21185)
    at /Users/careteen/Desktop/sohu/fe-base/FocusAppToolkit/renderer/node_modules/@builder/pack/deps/webpack-chain/Config.js:1:15266
    at Array.map (<anonymous>)
    at e.exports.toConfig (/Users/careteen/Desktop/sohu/fe-base/FocusAppToolkit/renderer/node_modules/@builder/pack/deps/webpack-chain/Config.js:1:15257)
    at /Users/careteen/Desktop/sohu/fe-base/FocusAppToolkit/renderer/node_modules/@builder/user-config/lib/userConfig/polyfill.js:34:32
    at configWebpack (/Users/careteen/Desktop/sohu/fe-base/FocusAppToolkit/renderer/node_modules/@builder/user-config/lib/applyUserConfig.js:43:21)
    at BuildService.<anonymous> (/Users/careteen/Desktop/sohu/fe-base/FocusAppToolkit/renderer/node_modules/build-scripts/lib/core/Context.js:587:27)
    at Generator.next (<anonymous>)
    at /Users/careteen/Desktop/sohu/fe-base/FocusAppToolkit/renderer/node_modules/build-scripts/lib/core/Context.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/careteen/Desktop/sohu/fe-base/FocusAppToolkit/renderer/node_modules/build-scripts/lib/core/Context.js:4:12)
    at BuildService.runConfigWebpack (/Users/careteen/Desktop/sohu/fe-base/FocusAppToolkit/renderer/node_modules/build-scripts/lib/core/Context.js:577:16)
    at BuildService.<anonymous> (/Users/careteen/Desktop/sohu/fe-base/FocusAppToolkit/renderer/node_modules/build-scripts/lib/core/Context.js:475:36)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/careteen/Desktop/sohu/fe-base/FocusAppToolkit/renderer/node_modules/build-scripts/lib/core/Context.js:5:58)

![screenshot-20211202-142634](https://user-images.githubusercontent.com/23131426/144369443-9ae05916-b51c-4847-8079-c59fe5810736.png)

**Comment by kisstar** [comment]
我也遇到了这个问题！😔

**Comment by simmzl** [comment]
+1

**Comment by wuwei111467** [comment]
我也遇到这个问题了
